openapi: 3.0.3
info:
  title: AutoOfficeAPI
  description: sheremetev.aoserver.ru
  version: 1.0.0
servers:
- url: https://sheremetev.aoserver.ru?r=api/apps
- url: https://arsamandi.aoserver.ru?r=api/apps
- url: https://sonyatrue.aoserver.ru?r=api/apps

tags:
- name: help
  description: Help
- name: user
  description: User
- name: goods
  description: Goods
- name: good
  description: Good
- name: lessons
  description: Lessons
- name: lesson
  description: Lesson

paths:

  /help/:
    post:
      tags:
        - help
      summary: getHelp
      operationId: getHelp
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Help'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'



  /json/:
    post:
      tags:
      - user
      summary: getUserData
      operationId: getUserData
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /json1/:
    post:
      tags:
      - goods
      summary: getUserGoods
      operationId: getUserGoods
      requestBody:
        $ref: '#/components/requestBodies/Goods'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsInfo'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'


components:
  schemas:

    Help:
      type: object
      properties:
        content:
          type: string

    UserInfo:
      type: object
      properties:
        last_name:
          type: string
        name:
          type: string
        middle_name:
          type: string
        image:
          type: string
        phone_number:
          type: string
        error:
          type: string

    GoodsInfo:
      type: object
      properties:
        id_goods:
          type: integer
        name:
          type: string
        creationDate:
          type: string
        image:
          type: string
        trainingId:
          type: integer
        idFavorite:
          type: integer

    User:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        method:
          type: string


    Goods:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        method:
          type: string

    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer


  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

    Goods:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Goods'
