//
// GoodsInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GoodsInfo: Codable, Hashable {

    public var idGoods: Int?
    public var name: String?
    public var creationDate: String?
    public var image: String?
    public var trainingId: Int?
    public var idFavorite: Int?

    public init(idGoods: Int? = nil, name: String? = nil, creationDate: String? = nil, image: String? = nil, trainingId: Int? = nil, idFavorite: Int? = nil) {
        self.idGoods = idGoods
        self.name = name
        self.creationDate = creationDate
        self.image = image
        self.trainingId = trainingId
        self.idFavorite = idFavorite
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case idGoods = "id_goods"
        case name
        case creationDate
        case image
        case trainingId
        case idFavorite
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(idGoods, forKey: .idGoods)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(trainingId, forKey: .trainingId)
        try container.encodeIfPresent(idFavorite, forKey: .idFavorite)
    }
}

