//
// GoodsInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GoodsInfo: Codable, Hashable, Identifiable {

    public var id = UUID()
    public var idGoods: String?
    public var goods: String?
    public var creationDate: String?
    public var image: String?
    public var idTraining: String?

    public init(idGoods: String? = nil, goods: String? = nil, creationDate: String? = nil, image: String? = nil, idTraining: String? = nil) {
        self.idGoods = idGoods
        self.goods = goods
        self.creationDate = creationDate
        self.image = image
        self.idTraining = idTraining
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case idGoods = "id_goods"
        case goods
        case creationDate = "creation_date"
        case image
        case idTraining = "id_training"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(idGoods, forKey: .idGoods)
        try container.encodeIfPresent(goods, forKey: .goods)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(idTraining, forKey: .idTraining)
    }
}

