//
// UserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserInfo: Codable, Hashable {

    public var lastName: String?
    public var name: String?
    public var middleName: String?
    public var image: String?
    public var phoneNumber: String?
    public var error: String?

    public init(lastName: String? = nil, name: String? = nil, middleName: String? = nil, image: String? = nil, phoneNumber: String? = nil, error: String? = nil) {
        self.lastName = lastName
        self.name = name
        self.middleName = middleName
        self.image = image
        self.phoneNumber = phoneNumber
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastName = "last_name"
        case name
        case middleName = "middle_name"
        case image
        case phoneNumber = "phone_number"
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(middleName, forKey: .middleName)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

